[2025-01-12T17:22:26.036+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-12T17:22:26.060+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xgboost_drift_pipeline.test_prediction_after_retrain manual__2025-01-12T17:22:13.572963+00:00 [queued]>
[2025-01-12T17:22:26.071+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xgboost_drift_pipeline.test_prediction_after_retrain manual__2025-01-12T17:22:13.572963+00:00 [queued]>
[2025-01-12T17:22:26.073+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-12T17:22:26.092+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_prediction_after_retrain> on 2025-01-12 17:22:13.572963+00:00
[2025-01-12T17:22:26.105+0000] {standard_task_runner.py:72} INFO - Started process 251 to run task
[2025-01-12T17:22:26.109+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'xgboost_drift_pipeline', 'test_prediction_after_retrain', 'manual__2025-01-12T17:22:13.572963+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/train_xgboost_pipeline.py', '--cfg-path', '/tmp/tmpo2sgxgwe']
[2025-01-12T17:22:26.113+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask test_prediction_after_retrain
[2025-01-12T17:22:26.134+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-12T17:22:26.174+0000] {task_command.py:467} INFO - Running <TaskInstance: xgboost_drift_pipeline.test_prediction_after_retrain manual__2025-01-12T17:22:13.572963+00:00 [running]> on host 42dc6dafdabb
[2025-01-12T17:22:26.276+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xgboost_drift_pipeline' AIRFLOW_CTX_TASK_ID='test_prediction_after_retrain' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T17:22:13.572963+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-12T17:22:13.572963+00:00'
[2025-01-12T17:22:26.278+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-12T17:22:26.295+0000] {train_xgboost_pipeline.py:848} INFO - Testing prediction on current data...
[2025-01-12T17:22:26.323+0000] {train_xgboost_pipeline.py:674} INFO - Downloaded data/Ingestion/Financial_with_Sentiment_pseudo.csv from MinIO to /tmp/Financial_with_Sentiment_pseudo.csv
[2025-01-12T17:22:26.344+0000] {train_xgboost_pipeline.py:674} INFO - Downloaded data/Ingestion/retrained_model_test.pkl from MinIO to /tmp/retrained_model_test.pkl
[2025-01-12T17:22:26.375+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:694 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-01-12T17:22:26.410+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:694 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-01-12T17:22:26.424+0000] {train_xgboost_pipeline.py:876} INFO - Test Prediction Evaluation - MSE: 82.11, R2: 0.62
[2025-01-12T17:22:26.425+0000] {logging_mixin.py:190} INFO - Test Prediction Metrics:
MSE: 82.11
R2: 0.62
[2025-01-12T17:22:26.426+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-12T17:22:26.441+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-12T17:22:26.442+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=xgboost_drift_pipeline, task_id=test_prediction_after_retrain, run_id=manual__2025-01-12T17:22:13.572963+00:00, execution_date=20250112T172213, start_date=20250112T172226, end_date=20250112T172226
[2025-01-12T17:22:26.484+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-12T17:22:26.502+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-12T17:22:26.504+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
